apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deployment
  labels:
    app: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: expapi
          image: %ECR_URI%
          ports:
            - containerPort: 80
